### ISSUE TITLE
review for JOSS (3/5): tests

### ISSUE THREAD

**Issue by bbolker** [oliviergimenez/GammaGompertzCR#4]
The package contains no tests.  This could be done by the standard old-school R approach (`.R` files in `tests/`), or via the `testthat` unit-testing framework.

Some thought will have to be given to the degree of reproducibility required (tolerances, random-number seed setting for JAGS, etc.) and to how to make the tests run fast enough (e.g. run for minimal numbers of steps).

The manual example in the `README` file does serve as a minimal example to make sure the software runs, but it does not show output (nor set random-number seeds) so there is no way to know if the output obtained is correct.

There are also no examples given in the manual.  The examples given in the `README` file should probably be incorporated in the package help pages.

**Comment by bbolker** [comment]
The authors say:

> The package contains only 3 functions and is basically a wrapper for the dcmle::jags.parfit function for fitting a Gompertz model to capture-recapture data. We now provide in the Readme and paper the results of the full analyses of a dataset (numerical outputs and figures) that can be used as a validation for users. Hopefully, this will do the same job as unit tests would do.

I still don't think this really fulfils the task of tests (either unit or integration). How will you know in future if changes to JAGS, or changes that you make to the code, keep the behaviour consistent?

**Comment by oliviergimenez** [comment]
By comparing the new results to the results provided in the paper (Table 1) I guess. It would mean making sure that the data haven't changed, by including a test maybe? Apologies if my answer sounds naive, I'm not so familiar with testing.

**Comment by bbolker** [comment]
I guess I'm looking for something more automated: you say `./run_test` from the command line and it runs some code and says "yes, these results match the reference results I have stored" or "no, tests failed". It would fail if the data changed *or* the algorithm changed. You could always update the stored reference results if you made a deliberate change in the data or in the algorithm.

**Comment by oliviergimenez** [comment]
I understand. I'll work on it. Thanks!

**Comment by oliviergimenez** [comment]
Hi @bbolker,
I have added a test for the main function fit_ggcr; devtools::test() runs ok.
Cheers,
Olivier

**Comment by bbolker** [comment]
great!
