### ISSUE TITLE
review for JOSS (4/5): documentation of functionality

### ISSUE THREAD

**Issue by bbolker** [oliviergimenez/GammaGompertzCR#5]
The documentation of the functionality in the package is relatively sparse. The minimal pieces are there (README and help pages for the three functions contained in the package), and there are pointers to the literature so that users can in principle go educate themselves on the technical details underpinning the computations.  However, what's here is extremely bare-bones, and it would be kind to users to give them a bit more help:

- describe the level of expertise in Bayesian MCMC techniques expected as a prerequisite for using the package safely (and possibly pointers to ecologist-friendly introductions by Kéry, McCarthy, ...). For example, users need to know how to interpret standard MCMC diagnostics (trace plots, Gelman-Rubin statistics, etc.) and what to do when they fail.
- Are there any diagnostics (e.g., sensible ranges of parameters) that are specific to this model, as opposed to the general tools that apply to most MCMC approaches?)
- What priors are used? Are the results sensitive to the priors? Can users override the default priors? When might they want to?
- How are initial values chosen for the chains? Can users override the defaults? When might they want to?
- Are there reasonable minimum and maximum data set sizes for this approach?
- Is there any capability for including fixed-effect covariates or random-effects groupings in the model? (I realize this may be beyond the scope of this package, but it might be worth mentioning)

**Comment by bbolker** [comment]
The README example doesn't work without running `library(dclone)` in the session first.

How is the number of cores for a parallel run determined? Is this something you want to give some hints to the user about? (On my system, without setting any options about the number of cores available, the example takes 8 minutes to run ...)

The style in the README file isn't completely consistent; for examples, assignments are sometimes `=` and sometimes `<-` (I prefer ` <- ` , i.e. arrows with spaces around them ...)

I *think* the code on l. 208 of the README file is intended to spit out a string that can be cut-and-pasted into the R console? (1) `paste(sprintf("post_inf[[%d]]",seq_along(clo)),collapse="")` would do the same thing slightly more elegantly ...); (2) `do.call(dctable,post_inf)` is the simple, idiomatic way to do this  ... or convince the `dclone` maintainers to allow `x` to be a list, which would then be expanded ...

**Comment by oliviergimenez** [comment]
Hi @bbolker,
The README file is working now.
We have added a section `How to choose the precision, number of iterations and clones?` to hints to the user.
The style was fixed, ` <- ` is used everywhere.
Thanks for your tip on using `do.call`.
Now working on the tests.
Thanks for your help.

**Comment by bbolker** [comment]
sounds good.
